version: '2'
services:
  app1:
    build: .
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    command: bash -c "while ! nc -z mysql 3306 > /dev/null; do echo waiting for mysql; sleep 5; done; npm run migrate && npm run seeds && node app/index.js"
  app2:
    build: .
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "8000:3000"
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql/init.d:/docker-entrypoint-initdb.d
